### PR TITLE
feat: update sigma version and support edge events

### PR DESCRIPTION
**Pull request by akitaSummer**
I updated the sigma version to 2.1.1, because sigma 2.1.1 added edge events

### CODE REVIEW

**Comment by Frida0** [comment]
hi @sim51, when will this PR be merged? We also need this new feature of sigma.js, what's more, I also need a "doubleClick" event in mouseEvents, I can create a PR for my requirement after this PR has been merged. Thanks.

**Comment by akitaSummer** [comment]
@Frida0 I apologize for my carelessness, I have added double click event.😅

**Comment by sim51** [comment]
PR is merged.
I added/checked all the new Sigma events.
Will be part of the v12.2

**Comment by Frida0** [comment]
@akitaSummer @sim51 thanks.

**Pull request merged**
